/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotesRouteImport } from './routes/votes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesIndexRouteImport } from './routes/votes/index'
import { Route as VotesNewRouteImport } from './routes/votes/new'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as VotesIdVotingRouteImport } from './routes/votes/$id.voting'
import { Route as VotesIdResultRouteImport } from './routes/votes/$id.result'

const VotesRoute = VotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIndexRoute = VotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VotesRoute,
} as any)
const VotesNewRoute = VotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VotesRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIdVotingRoute = VotesIdVotingRouteImport.update({
  id: '/$id/voting',
  path: '/$id/voting',
  getParentRoute: () => VotesRoute,
} as any)
const VotesIdResultRoute = VotesIdResultRouteImport.update({
  id: '/$id/result',
  path: '/$id/result',
  getParentRoute: () => VotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/votes': typeof VotesRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/votes/new': typeof VotesNewRoute
  '/votes/': typeof VotesIndexRoute
  '/votes/$id/result': typeof VotesIdResultRoute
  '/votes/$id/voting': typeof VotesIdVotingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/votes/new': typeof VotesNewRoute
  '/votes': typeof VotesIndexRoute
  '/votes/$id/result': typeof VotesIdResultRoute
  '/votes/$id/voting': typeof VotesIdVotingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/votes': typeof VotesRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/votes/new': typeof VotesNewRoute
  '/votes/': typeof VotesIndexRoute
  '/votes/$id/result': typeof VotesIdResultRoute
  '/votes/$id/voting': typeof VotesIdVotingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/votes'
    | '/demo/tanstack-query'
    | '/votes/new'
    | '/votes/'
    | '/votes/$id/result'
    | '/votes/$id/voting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/votes/new'
    | '/votes'
    | '/votes/$id/result'
    | '/votes/$id/voting'
  id:
    | '__root__'
    | '/'
    | '/votes'
    | '/demo/tanstack-query'
    | '/votes/new'
    | '/votes/'
    | '/votes/$id/result'
    | '/votes/$id/voting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VotesRoute: typeof VotesRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/votes': {
      id: '/votes'
      path: '/votes'
      fullPath: '/votes'
      preLoaderRoute: typeof VotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/': {
      id: '/votes/'
      path: '/'
      fullPath: '/votes/'
      preLoaderRoute: typeof VotesIndexRouteImport
      parentRoute: typeof VotesRoute
    }
    '/votes/new': {
      id: '/votes/new'
      path: '/new'
      fullPath: '/votes/new'
      preLoaderRoute: typeof VotesNewRouteImport
      parentRoute: typeof VotesRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/$id/voting': {
      id: '/votes/$id/voting'
      path: '/$id/voting'
      fullPath: '/votes/$id/voting'
      preLoaderRoute: typeof VotesIdVotingRouteImport
      parentRoute: typeof VotesRoute
    }
    '/votes/$id/result': {
      id: '/votes/$id/result'
      path: '/$id/result'
      fullPath: '/votes/$id/result'
      preLoaderRoute: typeof VotesIdResultRouteImport
      parentRoute: typeof VotesRoute
    }
  }
}

interface VotesRouteChildren {
  VotesNewRoute: typeof VotesNewRoute
  VotesIndexRoute: typeof VotesIndexRoute
  VotesIdResultRoute: typeof VotesIdResultRoute
  VotesIdVotingRoute: typeof VotesIdVotingRoute
}

const VotesRouteChildren: VotesRouteChildren = {
  VotesNewRoute: VotesNewRoute,
  VotesIndexRoute: VotesIndexRoute,
  VotesIdResultRoute: VotesIdResultRoute,
  VotesIdVotingRoute: VotesIdVotingRoute,
}

const VotesRouteWithChildren = VotesRoute._addFileChildren(VotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VotesRoute: VotesRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
